package:
  name: perl-config-autoconf
  version: "0.319"
  epoch: 0
  description: Config::AutoConf - A module to implement some of AutoConf macros in pure perl
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ambs/Config-AutoConf.git
      expected-commit: 7acb5b386469f68ecb344ccdaff7193a8869bdd8
      tag: ${{package.version}}

  - runs: PERL_MM_USE_DEFAULT=1 perl Makefile.PL

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-config-autoconf-doc
    pipeline:
      - uses: split/manpages
    description: perl-config-autoconf manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: ambs/Config-AutoConf
    use-tag: true
