package:
  name: perl-file-libmagic
  version: "1.23"
  epoch: 0
  description: File::LibMagic - Determine MIME types of data or files using libmagic
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl-dev
      - perl-config-autoconf 
      - perl-capture-tiny
      - libmagic-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/houseabsolute/File-LibMagic.git
      expected-commit: ab55dcf3fef341c2bcf22c8ef497cca7b8eee4d7
      tag: v${{package.version}}

  - runs: PERL_MM_USE_DEFAULT=1 perl Makefile.PL

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

  - uses: strip

subpackages:
  - name: perl-file-libmagic-doc
    pipeline:
      - uses: split/manpages
    description: perl-file-libmagic manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  github:
    identifier: houseabsolute/File-LibMagic
    strip-prefix: v
    use-tag: true
    tag-filter: v
# test:
#   pipeline:
#     - uses: test/tw/ldd-check
